### ISSUE TITLE
Adjective and nouns combinations and optional default dictionary inclusion

### ISSUE THREAD

**Issue by bostjan-cigan** [subhamg/unique-username-generator#10]
Hi guys! Love the work on this project and how it's structured!

The current dictionary can still lead to some combinations that might be though of as offensive or at least semi-offensive to some people.

Also it would be really great if the adjectives and nouns data were a separate package for people who might not want to use the default set (that would also keep the library size at a minimum).

If you think these two suggestions are helpful, I could help with a PR if needed :smile:

**Comment by subhamg** [comment]
Please create PR for @unique-username-generator/dictionary.

**Comment by bostjan-cigan** [comment]
I can't create a PR, only a separate repo. Do you want me to do that? Create a separate repository (NPM package) just for the dictionary and then a PR here for the changes needed to use that dictionary?

**Comment by subhamg** [comment]
Please use this https://github.com/subhamg/unique-username-generator-dictionary/invitations
