### ISSUE TITLE
Remove profanity and perversion from the list

### ISSUE THREAD

**Issue by artjom-mashanin** [subhamg/unique-username-generator#26]
We've been using this package in our product and we've noticed that it can have some bizzare names like `pornographic pervert`, `promiscuous  incest`, `sinister suicide`, etc etc etc

I think it would be great to either remove those, or add an option to avoid profanity and bizarre words in the generated strings

**Comment by karltaylor** [comment]
This is just turned me off from this project. Would be great if this can be fixed.

**Comment by jdturnbull** [comment]
Had this issue as well, quite surprised profanity wasn't excluded on release

**Comment by tslater** [comment]
Yeah I saw "orgasm", "orgy", and "homosexual". I was hoping for a list of clean nouns.

**Comment by stefansurkamp** [comment]
Looks like this package is no longer maintained properly. I saw @LiorKovalio did a bunch of improvements. Would you consider re-publishing the package? 🤔

**Comment by ologbonowiwi** [comment]
lol, it totally sucks see this here. #28 created to address some of the words.

if this don't get merged someone should probably create a new lib without the ensh*ttification

**Comment by muhashi** [comment]
[I made my own version](https://github.com/muhashi/generate-random-username) without any profanities since this made the package unusable to me

**Comment by subhamg** [comment]
This issue is fixed in pr #28

**Comment by ologbonowiwi** [comment]
hey @subhamg, thanks for approving the pr!

still, I think it may be better to leave this open, as there are thousands of words and I was able to remove only a few of them.
