### ISSUE TITLE
Cannot read properties of undefined (reading 'generateFromEmail')

### ISSUE THREAD

**Issue by si-le-mao** [subhamg/unique-username-generator#3]
I can't using the library. I always show the following error here.

Add library

```
import genUsername from "unique-username-generator";
```

Using

```
const username = genUsername.generateFromEmail('hello@example.com',3);
```

Throw an error

```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'generateFromEmail')
```

Thank you

**Comment by realmarcos** [comment]
i had the same problem. 
my solution was: 
`import { generateFromEmail } from "unique-username-generator";`

` const username = generateFromEmail(email, 3);`
