### ISSUE TITLE
 const crypto = require("crypto");

### ISSUE THREAD

**Issue by msaadqureshi** [subhamg/unique-username-generator#5]
**i am using this package in React Native** 
error: Error: Unable to resolve module crypto from F:\RNproject\SGT\node_modules\unique-username-generator\dist\index.js: crypto could not be found within the project or in these directories:
  node_modules
  3 | exports.nouns = exports.adjectives = exports.uniqueUsernameGenerator = exports.generateUsername = exports.generateFromEmail = void 0;
  4 | const data_1 = require("./data");
**> 5 | const crypto = require("crypto");
    |                         ^**
  6 | const randomNumber = (maxNumber) => {

**Comment by saumik13** [comment]
have you been able to find a fix for this?

**Comment by shashigit107** [comment]
No, please help me

**Comment by dylangolow** [comment]
Check this comment for the solution: https://github.com/subhamg/unique-username-generator/issues/11#issuecomment-1452268491

**Comment by subhamg** [comment]
Hi Everyone,

Good news! The issue you reported has been resolved in version 1.2.0 of our library. We have updated the code to ensure compatibility with Node.js, and the randomInt function now works seamlessly in server-side environments.

Feel free to install the latest version (1.2.0), and you should no longer encounter the "randomInt window does not exist on Node.js" error.

Thank you for bringing this to our attention, and we appreciate your support!
