### ISSUE TITLE
crypto-browserify webpack pollyfill error & crypto.randomInt is not a function

### ISSUE THREAD

**Issue by Luk3-V** [subhamg/unique-username-generator#6]
Not sure if this is more of an issue with webpack but I get this error.

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }
```

I was able to fix it by adding `resolve.fallback: { "crypto": false }` to webpack.config.js. 
However now when using `generateFromEmail()` I'm getting an error in the browser console.
```
crypto.randomInt is not a function
```

**Comment by subhamg** [comment]
Hi @Luk3-V,

Good news! The issue you reported has been resolved. We have updated the code to ensure compatibility. Please try out the latest version. 

Thank you for bringing this to our attention, and we appreciate your support!
