### ISSUE TITLE
Not build properly?

### ISSUE THREAD

**Issue by baxevanis** [subhamg/unique-username-generator#8]
Hello
not 100% sure but when I install the package I do get the old dictionary with all the bad words inside! :/
I can verify that I do get the newer version but still the build seems to be based on the old version?

<img width="576" alt="Screenshot 2022-10-28 at 18 06 24" src="https://user-images.githubusercontent.com/3465085/198693197-be5aeb96-134e-4b97-a72c-580b81625d67.png">

<img width="1015" alt="Screenshot 2022-10-28 at 18 05 06" src="https://user-images.githubusercontent.com/3465085/198692971-3b9db8df-03b3-405d-a7a4-11ff14340bec.png">

Hope this helps!

and thank you for the library

**Comment by subhamg** [comment]
It's released today.
